### PR TITLE
SOL-82223: sampler to demonstrate partitionKey setting on outbound me…

### PR DESCRIPTION
**Pull request by mustafaal-sakkaf**

### CODE REVIEW

**Comment by TamimiGitHub** [comment]
Thanks for opening up the PR! I'm still yet to review the actual code but just FYI we will need to update the API version https://github.com/SolaceSamples/solace-samples-python/blob/main/requirements.txt#L7 if this requires an update

**Comment by mustafaal-sakkaf** [comment]
The python api with partitioned queue support has not been merged yet as it requires release of a new broker version...it might be better to leave this PR open until the official release of the feature.

**Comment by mustafaal-sakkaf** [comment]
@TamimiGitHub python api 1.5.0 has been released. I bumped the api version in requirements.txt.

**Review by TamimiGitHub — APPROVED** [review]
Thanks!

**Pull request merged**
